app/src/Entity/Machines.php
<?php

namespace App\Entity;

use App\Repository\MachinesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MachinesRepository::class)]
class Machines
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name_machine = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $number_machine = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $machine_picture = null;

    #[ORM\Column(nullable: true)]
    private ?bool $member_access = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_booked = null;

    #[ORM\ManyToOne(targetEntity: Workspaces::class, inversedBy: "machines")]
    private ?Workspaces $workspace = null;
    
    #[ORM\OneToMany(mappedBy: "machine", targetEntity: "App\Entity\Reservations", cascade: ['persist', 'remove'])]
    private Collection $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    /**
     * @return Collection|Reservations[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservations $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setMachine($this);
        }

        return $this;
    }

    public function removeReservation(Reservations $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getMachine() === $this) {
                $reservation->setMachine(null);
            }
        }

        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameMachine(): ?string
    {
        return $this->name_machine;
    }

    public function setNameMachine(string $name_machine): static
    {
        $this->name_machine = $name_machine;

        return $this;
    }

    public function getNumberMachine(): ?string
    {
        return $this->number_machine;
    }

    public function setNumberMachine(?string $number_machine): static
    {
        $this->number_machine = $number_machine;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getMachinePicture(): ?string
    {
        return $this->machine_picture;
    }

    public function setMachinePicture(?string $machine_picture): static
    {
        $this->machine_picture = $machine_picture;

        return $this;
    }

    public function isMemberAccess(): ?bool
    {
        return $this->member_access;
    }

    public function setMemberAccess(?bool $member_access): static
    {
        $this->member_access = $member_access;

        return $this;
    }

    public function isIsBooked(): ?bool
    {
        return $this->is_booked;
    }

    public function setIsBooked(?bool $is_booked): static
    {
        $this->is_booked = $is_booked;

        return $this;
    }

    public function getWorkspace(): ?Workspaces
    {
        return $this->workspace;
    }

    public function setWorkspace(?Workspaces $workspace): static
    {
        $this->workspace = $workspace;

        return $this;
    }
}

app/src/Form/MachinesType.php
<?php

namespace App\Form;

use App\Entity\Machines;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;

class MachinesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_machine', TextType::class, [
                'label' => 'Nom de la machine',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez entrer un nom pour la machine.',
                    ]),
                    new Length([
                        'max' => 50,
                        'maxMessage' => 'Le nom de la machine ne peut pas dépasser {{ limit }} caractères.',
                    ])
                ],
            ])
            ->add('number_machine', TextType::class, [
                'label' => 'Numéro de la machine',
                'required' => false,
                'constraints' => [
                    new Length([
                        'max' => 50,
                        'maxMessage' => 'Le numéro de la machine ne peut pas dépasser {{ limit }} caractères.',
                    ])
                ],
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description',
                'required' => false,
                'constraints' => [
                    new Length([
                        'max' => 255,
                        'maxMessage' => 'La description ne peut pas dépasser {{ limit }} caractères.',
                    ])
                ],
            ])
            ->add('machine_picture', FileType::class, [
                'label' => 'Image de la machine',
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Veuillez télécharger un fichier image valide (JPEG, PNG, GIF).',
                    ])
                ],
            ])
            ->add('member_access', CheckboxType::class, [
                'label' => 'Accès membre',
                'required' => false,
            ])
            ->add('is_booked', CheckboxType::class, [
                'label' => 'Réservé',
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Machines::class,
        ]);
    }
}

app/src/Controller/MachinesController.php
<?php

namespace App\Controller;

use App\Entity\Machines;
use App\Form\MachinesType;
use App\Repository\MachinesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/machines')]
class MachinesController extends AbstractController
{
    #[Route('/', name: 'app_machines_index', methods: ['GET'])]
    public function index(MachinesRepository $machinesRepository): Response
    {
        return $this->render('crudTemplates/machines/index.html.twig', [
            'machines' => $machinesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_machines_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $machine = new Machines();
        $form = $this->createForm(MachinesType::class, $machine);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($machine);
            $entityManager->flush();

            return $this->redirectToRoute('app_machines_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('crudTemplates/machines/new.html.twig', [
            'machine' => $machine,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_machines_show', methods: ['GET'])]
    public function show(Machines $machine): Response
    {
        return $this->render('crudTemplates/machines/show.html.twig', [
            'machine' => $machine,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_machines_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Machines $machine, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MachinesType::class, $machine);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_machines_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('crudTemplates/machines/edit.html.twig', [
            'machine' => $machine,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_machines_delete', methods: ['POST'])]
    public function delete(Request $request, Machines $machine, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$machine->getId(), $request->request->get('_token'))) {
            $entityManager->remove($machine);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_machines_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/crudTemplates/machines/_delete_form.html.twig
<form method="post" action="{{ path('app_machines_delete', {'id': machine.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ machine.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/crudTemplates/machines/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/crudTemplates/machines/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Machines{% endblock %}

{% block body %}
    <h1>Edit Machines</h1>

    {{ include('/crudTemplates/machines/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_machines_index') }}">back to list</a>

    {{ include('/crudTemplates/machines/_delete_form.html.twig') }}
{% endblock %}

app/templates/crudTemplates/machines/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Machines index{% endblock %}

{% block body %}
    <h1>Machines index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_machine</th>
                <th>Number_machine</th>
                <th>Description</th>
                <th>Machine_picture</th>
                <th>Member_access</th>
                <th>Is_booked</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for machine in machines %}
            <tr>
                <td>{{ machine.id }}</td>
                <td>{{ machine.nameMachine }}</td>
                <td>{{ machine.numberMachine }}</td>
                <td>{{ machine.description }}</td>
                <td>{{ machine.machinePicture }}</td>
                <td>{{ machine.memberAccess ? 'Yes' : 'No' }}</td>
                <td>{{ machine.isBooked ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_machines_show', {'id': machine.id}) }}">show</a>
                    <a href="{{ path('app_machines_edit', {'id': machine.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_machines_new') }}">Create new</a>
{% endblock %}

app/templates/crudTemplates/machines/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Machines{% endblock %}

{% block body %}
    <h1>Create new Machines</h1>

    {{ include('/crudTemplates/machines/_form.html.twig') }}

    <a href="{{ path('app_machines_index') }}">back to list</a>
{% endblock %}

app/templates/crudTemplates/machines/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Machines{% endblock %}

{% block body %}
    <h1>Machines</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ machine.id }}</td>
            </tr>
            <tr>
                <th>Name_machine</th>
                <td>{{ machine.nameMachine }}</td>
            </tr>
            <tr>
                <th>Number_machine</th>
                <td>{{ machine.numberMachine }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ machine.description }}</td>
            </tr>
            <tr>
                <th>Machine_picture</th>
                <td>{{ machine.machinePicture }}</td>
            </tr>
            <tr>
                <th>Member_access</th>
                <td>{{ machine.memberAccess ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_booked</th>
                <td>{{ machine.isBooked ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_machines_index') }}">back to list</a>

    <a href="{{ path('app_machines_edit', {'id': machine.id}) }}">edit</a>

    {{ include('/crudTemplates/machines/_delete_form.html.twig') }}
{% endblock %}