app/src/Entity/Consummables.php
<?php

namespace App\Entity;

use App\Repository\ConsummablesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConsummablesRepository::class)]
class Consummables
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name_consummable = null;

    #[ORM\Column(nullable: true)]
    private ?float $quantity = null;

    #[ORM\Column(nullable: true)]
    private ?float $threshold = null;

    #[ORM\ManyToOne]
    private ?CatConsummables $cat_consummables = null;

    #[ORM\ManyToOne]
    private ?UnitsConsummable $unit_consummables = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameConsummable(): ?string
    {
        return $this->name_consummable;
    }

    public function setNameConsummable(string $name_consummable): static
    {
        $this->name_consummable = $name_consummable;

        return $this;
    }

    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    public function setQuantity(?float $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getThreshold(): ?float
    {
        return $this->threshold;
    }

    public function setThreshold(?float $threshold): static
    {
        $this->threshold = $threshold;

        return $this;
    }

    public function getCatConsummables(): ?CatConsummables
    {
        return $this->cat_consummables;
    }

    public function setCatConsummables(?CatConsummables $cat_consummables): static
    {
        $this->cat_consummables = $cat_consummables;

        return $this;
    }

    public function getUnitConsummables(): ?UnitsConsummable
    {
        return $this->unit_consummables;
    }

    public function setUnitConsummables(?UnitsConsummable $unit_consummables): static
    {
        $this->unit_consummables = $unit_consummables;

        return $this;
    }

}

app/src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name_event = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $start_date = null;


    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $end_date = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $end_hour = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $front_media = null;

    #[ORM\Column(type: "boolean", nullable: true)]
    private ?bool $is_published = null;

    #[ORM\Column]
    private ?bool $is_member_only = null;

    #[ORM\Column(nullable: true)]
    private ?int $max_participants = null;

    public function __construct()
    {
        $this->is_published = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameEvent(): ?string
    {
        return $this->name_event;
    }

    public function setNameEvent(string $name_event): static
    {
        $this->name_event = $name_event;

        return $this;
    }

    public function getStartDate(): ?\DateTime
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTime $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTime
    {
        return $this->end_date;
    }



    public function setEndDate(?\DateTime $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }


    public function getStartHour(): ?\DateTime
    {
        return $this->start_hour;
    }

    public function setStartHour(?string $start_hour): static
    {
        $this->start_hour = $start_hour ? new \DateTime($start_hour) : null;

        return $this;
    }

    public function getEndHour(): ?\DateTime
    {
        return $this->end_hour;
    }

    public function setEndHour(?string $end_hour): static
    {
        $this->end_hour = $end_hour ? new \DateTime($end_hour) : null;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getFrontMedia(): ?string
    {
        return $this->front_media;
    }

    public function setFrontMedia(?string $front_media): static
    {
        $this->front_media = $front_media;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }
    

    public function setIsPublished(bool $is_published): static
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function isIsMemberOnly(): ?bool
    {
        return $this->is_member_only;
    }
    

    public function setIsMemberOnly(bool $is_member_only): static
    {
        $this->is_member_only = $is_member_only;

        return $this;
    }

    public function getMaxParticipants(): ?int
    {
        return $this->max_participants;
    }

    public function setMaxParticipants(?int $max_participants): static
    {
        $this->max_participants = $max_participants;

        return $this;
    }
}

app/src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'Il y a déjà un compte avec ce nom utilisateur !')]
class Users extends Persons implements UserInterface, PasswordAuthenticatedUserInterface
{
    // #[ORM\Id]
    // #[ORM\GeneratedValue]
    // #[ORM\Column]
    // private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $birthday = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $street = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $adress_complement = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_organization = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_email_verified = null;

    #[ORM\Column(type: 'string', length: 100)]
    private $resetToken;

    #[ORM\Column(nullable: true)]
    private ?bool $is_validated = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $first_membership = null;
    

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $last_membership = null;

    #[ORM\ManyToMany(targetEntity: Consummables::class)]
    private Collection $consummable;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $num_siret = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $name_organization = null;

    public function __construct()
    {
        $this->consummable = new ArrayCollection();
    }

    // public function getId(): ?int
    // {
    //     return $this->id;
    // }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getBirthday(): ?\DateTime
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTime $birthday): static
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getAdressComplement(): ?string
    {
        return $this->adress_complement;
    }

    public function setAdressComplement(?string $adress_complement): static
    {
        $this->adress_complement = $adress_complement;

        return $this;
    }

    public function isIsOrganization(): ?bool
    {
        return $this->is_organization;
    }

    public function setIsOrganization(?bool $is_organization): static
    {
        $this->is_organization = $is_organization;

        return $this;
    }

    public function isIsEmailVerified(): ?bool
    {
        return $this->is_email_verified;
    }
    

    public function setIsEmailVerified(?bool $is_email_verified): static
    {
        $this->is_email_verified = $is_email_verified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function isIsValidated(): ?bool
    {
        return $this->is_validated;
    }

    public function setIsValidated(bool $is_validated): static
    {
        $this->is_validated = $is_validated;

        return $this;
    }

    public function getFirstMembership(): ?\DateTime
    {
        return $this->first_membership;
    }

    public function setFirstMembership(?\DateTime $first_membership): static
    {
        $this->first_membership = $first_membership;

        return $this;
    }

    public function getLastMembership(): ?\DateTime
    {
        return $this->last_membership;
    }

    public function setLastMembership(?\DateTime $last_membership): static
    {
        $this->last_membership = $last_membership;

        return $this;
    }

    /**
     * @return Collection<int, Consummables>
     */
    public function getConsummable(): Collection
    {
        return $this->consummable;
    }

    public function addConsummable(Consummables $consummable): static
    {
        if (!$this->consummable->contains($consummable)) {
            $this->consummable->add($consummable);
        }

        return $this;
    }

    public function removeConsummable(Consummables $consummable): static
    {
        $this->consummable->removeElement($consummable);

        return $this;
    }

    public function getNumSiret(): ?string
    {
        return $this->num_siret;
    }

    public function setNumSiret(?string $num_siret): static
    {
        $this->num_siret = $num_siret;

        return $this;
    }

    public function getNameOrganization(): ?string
    {
        return $this->name_organization;
    }

    public function setNameOrganization(?string $name_organization): static
    {
        $this->name_organization = $name_organization;

        return $this;
    }
}

app/templates/admin_dashboard/index.html.twig
{% extends 'adminTemplatePage.html.twig' %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" href="{{ asset('assets/styles/articlesAdmin.css') }}">

{% endblock %}

{% block title %}Tableau de bord Administrateur{% endblock %}

{% block main %}
    <div class="container mt-4">
        <h1 class="mb-5">Tableau de bord Administrateur</h1>

        <div class="row mb-4">
            <div class="col-lg-6">
                <div class="card mb-3">
                    <div class="card-header">Statistiques Générales</div>
                    <div class="card-body">
                        <h5 class="card-title">Total Adhérents: {{ totalMembers }}</h5>
                        <h5 class="card-title">Total Réservations: {{ totalReservations }}</h5>
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">Statistiques des Machines</div>
                    <div class="card-body">
                        {% if machineUsageStats is not empty %}
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Machine</th>
                                    <th>Nombre de Réservations</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for stat in machineUsageStats %}
                                    <tr>
                                        <td>{{ stat.machineName }}</td>
                                        <td>{{ stat.reservationCount }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p>Aucune donnée d'utilisation des machines disponible.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


        <div class="row mb-2">
            <div class="col-lg-6">
                <div class="card mb-3">
                    <div class="card-header">Demande d'adhésion</div>
                    <div class="card-body">
                        {% if pendingMemberships is not empty %}
                            <ul class="list-group">
                                {% for member in pendingMemberships %}
                                    <li class="list-group-item">
                                        {{ member.lastname }} {{ member.firstname }}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>Aucune nouvelle adhésion récente.</p>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="card mb-3">
                    <div class="card-header">Fin d'adhésion</div>
                    <div class="card-body">
                        {% if endingMembership is not empty %}
                            <ul class="list-group">
                                {% for member in endingMembership %}
                                    <li class="list-group-item">
                                        {{ member.lastname }} {{ member.firstname }} - {{ member.lastMembership|date('Y-m-d')}}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>Aucune adhésion en fin de période.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">Réservations en Attente de Validation</div>
                    <div class="card-body">
                        {% if pendingValidations is not empty %}
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Event</th>
                                    <th>Workspace</th>
                                    <th>Machine</th>
                                    <th>Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for reservation in pendingValidations %}
                                    <tr>
                                        <td>{{ reservation.eventName }}</td>
                                        <td>{{ reservation.workspaceName }}</td>
                                        <td>{{ reservation.machineName }}</td>
                                        <td>{{ reservation.startDate|date('Y-m-d') }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p>Aucune réservation en attente de validation.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>



        <div class="row mb-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">Réservations à Venir</div>
                    <div class="card-body">
                        {% if upcomingReservations is not empty %}
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Event</th>
                                    <th>Workspace</th>
                                    <th>Machine</th>
                                    <th>Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for reservation in upcomingReservations %}
                                    <tr>
                                        <td>{{ reservation.eventName }}</td>
                                        <td>{{ reservation.workspaceName}}</td>
                                        <td>{{ reservation.machineName }}</td>
                                        <td>{{ reservation.startDate|date('Y-m-d') }}</td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p>Aucune réservation en attente de validation.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>









        <div class="card mb-4">
            <div class="card-header">Consommables au Seuil de Stock</div>
            <div class="card-body">
                {% if consumablesAtThreshold is not empty %}
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Quantité</th>
                            <th>Seuil</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for consumable in consumablesAtThreshold %}
                            <tr>
                                <td>{{ consumable.nameConsummable }}</td>
                                <td>{{ consumable.quantity }}</td>
                                <td>{{ consumable.threshold }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>Aucun consommable n'atteint le seuil de stock.</p>
                {% endif %}
            </div>
        </div>




    </div>
{% endblock %}
{% block scripts %}
    {{ parent() }}
    <script src="{{ asset('assets/javascript/articlesAdmin.js') }}"></script>
{% endblock %}