app/src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name_event = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $start_date = null;


    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $end_date = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $start_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $end_hour = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $front_media = null;

    #[ORM\Column(type: "boolean", nullable: true)]
    private ?bool $is_published = null;

    #[ORM\Column]
    private ?bool $is_member_only = null;

    #[ORM\Column(nullable: true)]
    private ?int $max_participants = null;

    public function __construct()
    {
        $this->is_published = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameEvent(): ?string
    {
        return $this->name_event;
    }

    public function setNameEvent(string $name_event): static
    {
        $this->name_event = $name_event;

        return $this;
    }

    public function getStartDate(): ?\DateTime
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTime $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTime
    {
        return $this->end_date;
    }



    public function setEndDate(?\DateTime $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }


    public function getStartHour(): ?\DateTime
    {
        return $this->start_hour;
    }

    public function setStartHour(?string $start_hour): static
    {
        $this->start_hour = $start_hour ? new \DateTime($start_hour) : null;

        return $this;
    }

    public function getEndHour(): ?\DateTime
    {
        return $this->end_hour;
    }

    public function setEndHour(?string $end_hour): static
    {
        $this->end_hour = $end_hour ? new \DateTime($end_hour) : null;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getFrontMedia(): ?string
    {
        return $this->front_media;
    }

    public function setFrontMedia(?string $front_media): static
    {
        $this->front_media = $front_media;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }
    

    public function setIsPublished(bool $is_published): static
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function isIsMemberOnly(): ?bool
    {
        return $this->is_member_only;
    }
    

    public function setIsMemberOnly(bool $is_member_only): static
    {
        $this->is_member_only = $is_member_only;

        return $this;
    }

    public function getMaxParticipants(): ?int
    {
        return $this->max_participants;
    }

    public function setMaxParticipants(?int $max_participants): static
    {
        $this->max_participants = $max_participants;

        return $this;
    }
}

app/src/Controller/AdminArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Publications; // Assurez-vous que cette entité est correcte pour votre contexte
use App\Form\PublicationsType; // Vérifiez si le formulaire doit être ajusté
use App\Repository\PublicationsRepository; // Confirmez le repository
use App\Service\FileUploader; // Confirmez que ce service est utilisé et configuré
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/admin/articles')]
class AdminArticlesController extends AbstractController
{
    #[Route('/', name: 'app_admin_articles_index', methods: ['GET'])]
    public function index(PublicationsRepository $publicationsRepository): Response
    {
        return $this->render('admin_articles/index.html.twig', [
            'publications' => $publicationsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_articles_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $publication = new Publications();
        $form = $this->createForm(PublicationsType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Logique d'upload de l'image et de persistance
            if ($imageFile = $form->get('front_picture_file')->getData()) {
                $imageFileName = $fileUploader->upload($imageFile);
                $publication->setFrontPicture($imageFileName);
            }

            $entityManager->persist($publication);
            $entityManager->flush();

            $this->addFlash('success', 'L\'article a bien été créé.');
            return $this->redirectToRoute('app_admin_articles_index');
        }

        return $this->render('admin_articles/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_admin_articles_show', methods: ['GET'])]
    public function show(Publications $publication): Response
    {
        return $this->render('admin_articles/show.html.twig', [
            'publication' => $publication,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_articles_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Publications $publication, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(PublicationsType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $oldImageFileName = $publication->getFrontPicture(); // Sauvegardez le nom de l'ancienne image
                if ($imageFile = $form->get('front_picture_file')->getData()) {
                    $imageFileName = $fileUploader->upload($imageFile);
                    $publication->setFrontPicture($imageFileName);

                    // Supprimez l'ancienne image si une nouvelle est téléchargée et différente
                    if ($oldImageFileName && $oldImageFileName !== $imageFileName) {
                        $oldImageFilePath = $this->getParameter('targetDirectory') . '/' . $oldImageFileName;
                        if (file_exists($oldImageFilePath)) {
                            unlink($oldImageFilePath);
                        }
                    }
                }

                $entityManager->flush();
                $this->addFlash('success', 'La publication a bien été modifiée.');
                return $this->redirectToRoute('app_admin_articles_show', ['id' => $publication->getId()], Response::HTTP_SEE_OTHER);
            } else {
                // Le formulaire a été soumis mais n'est pas valide
                $this->addFlash('danger', 'Une erreur est survenue lors de la modification!');
            }
        }

        return $this->render('admin_articles/edit.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }


    #[Route('/{id}', name: 'app_admin_articles_delete', methods: ['POST'])]
    public function delete(Request $request, Publications $publication, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $publication->getId(), $request->request->get('_token'))) {

            $imageFileName = $publication->getFrontPicture();
            if ($imageFileName) {
                $imageFilePath = $this->getParameter('targetDirectory') . '/' . $imageFileName;
                if (file_exists($imageFilePath)) {
                    unlink($imageFilePath);
                }
            }

            $entityManager->remove($publication);
            $entityManager->flush();

            $this->addFlash('success', 'Publication supprimée avec succès.');
        }

        return $this->redirectToRoute('app_admin_articles_index');
    }
}

app/templates/admin_articles/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_articles_delete', {'id': publication.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ publication.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

app/templates/admin_articles/_form.html.twig
{{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': ''}}) }}


<div class="mb-3">
	{{ form_label(form.title, 'Titre', {'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
	{{ form_errors(form.title) }}
</div>


<div class="mb-3">
	{{ form_label(form.front_picture_file, 'Image de couverture', {'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.front_picture_file, {'attr': {'class': 'form-control'}}) }}
	{{ form_errors(form.front_picture_file) }}
</div>

<div class="mb-3">
	{{ form_label(form.description, 'Description', {'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
	{{ form_errors(form.description) }}
</div>

<div class="mb-3">
	{{ form_label(form.media, 'Media (URL)', {'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.media, {'attr': {'class': 'form-control'}}) }}
	{{ form_errors(form.media) }}
</div>

<div class="mb-3">
	{{ form_label(form.date_publication, 'Date de publication', {'label_attr': {'class': 'form-label'}}) }}
	{{ form_widget(form.date_publication, {'attr': {'class': 'form-control', 'placeholder': 'YYYY-MM-DD', 'required': 'required'}}) }}
	{{ form_errors(form.date_publication) }}
</div>

<div class="mb-3">
	{{ form_label(form.user, 'Nom de l\'auteur', {'label_attr': {'class': 'form-label'}}) }}
    {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
    {{ form_errors(form.user) }}
</div>









<div class="mb-3">
    {{ form_label(form.is_published, 'Publié ?', {'label_attr': {'class': 'form-label'}}) }}
    <div class="form-check">
        {{ form_widget(form.is_published, {'attr': {'class': 'form-check-input'}}) }}
        {{ form_label(form.is_published, 'Oui', {'label_attr': {'class': 'form-check-label'}}) }}
        {{ form_errors(form.is_published) }}
    </div>
</div>

<button type="submit" class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>

{{ form_end(form) }}

app/templates/admin_articles/edit.html.twig
{% extends 'adminTemplatePage.html.twig' %}

{% block title %}Edit Publications
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('assets/styles/articlesVisitor.css') }}">
{% endblock %}

{% block main %}
<a role="button" class="btn btn-outline-primary btn-sm" href="{{ path('app_admin_articles_index') }}" style="border-radius:10%;">
    < Retour </a>
<div>
    <div class="mb-3">
        <h1>Edit Publications</h1>
    </div>
    <div class="d-flex align-items-center mb-3">
        {{ include('/admin_articles/_delete_form.html.twig') }}
    </div>
</div>



	{{ include('/admin_articles/_form.html.twig', {'button_label': 'Update'}) }}


{% endblock %}

app/templates/admin_articles/index.html.twig
{% extends 'adminTemplatePage.html.twig' %}

{% block stylesheets %}
	{{parent()}}
	<link rel="stylesheet" href="{{ asset('assets/styles/articlesAdmin.css') }}">
	
{% endblock %}

{% block title %}Gestions des Publications d'articles
{% endblock %}

{% block main %}
	{% include "components/_flash.html.twig" %}
	<div class="text-center">
		<h1>Articles Publiés</h1>
	</div>
	<div class="text-center mb-4">
		<input type="text" id="searchInput" class="form-control" placeholder="Rechercher par titre...">
	</div>

	<div class="mb-4 ">
		<a href="{{ path('app_admin_articles_new') }}" class="btn color-btnn ">Créer un nouveau article</a>
	</div>

	<div class="row row-cols-1 row-cols-md-3 g-4">
		{% for publication in publications %}
			{% if publication.isPublished %}
				<div class="col">
					<div class="card h-100" data-title="{{ publication.title | lower }}">
						{% if publication.frontPicture %}
							<img src="{{ asset('assets/uploads/' ~ publication.frontPicture) }}" class="card-img-top" alt="Image for {{ publication.title }}">
						{% endif %}
						<div class="card-body d-flex flex-column">
							<h5 class="card-title">{{ publication.title }}</h5>
							<p class="card-text">{{ publication.description|length > 100 ? publication.description|slice(0, 100) ~ '...' : publication.description }}</p>
							<div class="mt-auto form-group d-flex align-items-center justify-content-between">
								<a href="{{ path('app_admin_articles_show', {'id': publication.id}) }}" class="btn color-btnn">Détails</a>
								<a href="{{ path('app_admin_articles_edit', {'id': publication.id}) }}" class="btn btn-warning">Modifier</a>
							</div>
						</div>
					</div>
				</div>
			{% endif %}
		{% else %}
			<div class="col">
				<p>Pas de publication</p>
			</div>
		{% endfor %}
	</div>
	<div class="text-center">
		<h2 class="mt-5 mb-5">Articles non plublié</h2>
	</div>
	<div class="row row-cols-1 row-cols-md-3 g-4">
		{% for publication in publications %}
			{% if not publication.isPublished %}
				<div class="col">
					<div class="card h-100" data-title="{{ publication.title | lower }}">
						{% if publication.frontPicture %}
							<img src="{{ asset('assets/uploads/' ~ publication.frontPicture) }}" class="card-img-top" alt="Image for {{ publication.title }}">
						{% endif %}
						<div class="card-body d-flex flex-column">
							<h5 class="card-title">{{ publication.title }}</h5>
							<p class="card-text">{{ publication.description|length > 100 ? publication.description|slice(0, 100) ~ '...' : publication.description }}</p>
							<div class="mt-auto form-group d-flex align-items-center justify-content-between">
								<a href="{{ path('app_admin_articles_show', {'id': publication.id}) }}" class="btn color-btnn">Détails</a>
								<a href="{{ path('app_admin_articles_edit', {'id': publication.id}) }}" class="btn btn-warning">Modifier</a>
							</div>
						</div>
					</div>
				</div>
			{% endif %}
		{% else %}
			<div class="col">
				<p>No brouillon records found</p>
			</div>
		{% endfor %}
	</div>

{% endblock %}
{% block scripts %}
	{{ parent() }}
		<script src="{{ asset('assets/javascript/articlesAdmin.js') }}"></script>
{% endblock %}

app/templates/admin_articles/new.html.twig
{% extends 'adminTemplatePage.html.twig' %}


{% block title %}New Publications{% endblock %}

{% block main %}
    <h1>Create new Publications</h1>

    {{ include('/admin_articles/_form.html.twig') }}

    <a href="{{ path('app_admin_articles_index') }}">back to list</a>
{% endblock %}

app/templates/admin_articles/show.html.twig
{% extends 'adminTemplatePage.html.twig' %}

{% block title %}Publication :
	{{ publication.title }}
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('assets/styles/articlesVisitor.css') }}">
	<style>
		.publication-image {
			width: 25%; /* Définit la largeur de l'image à 50% */
			height: auto; /* Maintient l'aspect ratio de l'image */
			display: block; /* Assure que l'image est traitée comme un bloc pour la centrer correctement */
			margin: 0 auto; /* Centre l'image horizontalement */
		}
	</style>
{% endblock %}

{% block main %}
<a role="button" class="btn btn-outline-primary btn-sm" href="{{ path('app_admin_articles_index') }}" style="border-radius:10%;">
    < Retour </a>

	<div class="container mt-5">
		{% include "components/_flash.html.twig" %}

		<h1 class="mb-4">Publication :
			{{ publication.title }}</h1>

		<div class="card">
			{% if publication.frontPicture %}
				<img src="{{ asset('assets/uploads/' ~ publication.frontPicture) }}" class="card-img-top publication-image" alt="Image de {{ publication.title }}">
			{% endif %}
			<div class="card-body">
				<h5 class="card-title">Titre de l'article :
					{{ publication.title }}</h5>
				<p class="card-text">Description :
					{{ publication.description }}</p>
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item">ID :
					{{ publication.id }}</li>
				<li class="list-group-item">Date de publication :
					{{ publication.datePublication ? publication.datePublication|date('Y-m-d') : 'Non définie' }}</li>
				<li class="list-group-item">Publié :
					{{ publication.isPublished ? 'Oui' : 'Non' }}</li>
				{% if publication.media %}
					<li class="list-group-item">
						Média :
						<a href="{{ publication.media }}" target="_blank">Voir la vidéo</a>
					</li>
				{% endif %}
			</ul>
			<div class="card-body d-flex justify-content-between">
				<div>
					<a href="{{ path('app_admin_articles_edit', {'id': publication.id}) }}" class="btn btn-warning">Modifier</a>
				</div>
				<div class="ms-auto">
					{{ include('/admin_articles/_delete_form.html.twig') }}
				</div>
			</div>

		</div>
	</div>
{% endblock %}