app/src/Entity/UnitsConsummable.php
<?php

namespace App\Entity;

use App\Repository\UnitsConsummableRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UnitsConsummableRepository::class)]
class UnitsConsummable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name_unit = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameUnit(): ?string
    {
        return $this->name_unit;
    }

    public function setNameUnit(string $name_unit): static
    {
        $this->name_unit = $name_unit;

        return $this;
    }
}

app/src/Form/UnitsConsummableType.php
<?php

namespace App\Form;

use App\Entity\UnitsConsummable;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class UnitsConsummableType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('name_unit', TextType::class, [
            'label' => 'Nom de l\'unité',
            'attr' => [
                'class' => 'form-control mb-3',
                'placeholder' => 'Entrez le nom de l\'unité consommable',
            ],
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => UnitsConsummable::class,
        ]);
    }
}

app/src/Controller/UnitsConsummableController.php
<?php

namespace App\Controller;

use App\Entity\UnitsConsummable;
use App\Form\UnitsConsummableType;
use App\Repository\UnitsConsummableRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/units/consummable')]
class UnitsConsummableController extends AbstractController
{
    #[Route('/', name: 'app_units_consummable_index', methods: ['GET'])]
    public function index(UnitsConsummableRepository $unitsConsummableRepository): Response
    {
        return $this->render('admin_consummables/units_consummable/index.html.twig', [
            'units_consummables' => $unitsConsummableRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_units_consummable_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $unitsConsummable = new UnitsConsummable();
        $form = $this->createForm(UnitsConsummableType::class, $unitsConsummable);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($unitsConsummable);
            $entityManager->flush();
            $this->addFlash('success','Créer une unitée avec succes');
            return $this->redirectToRoute('app_units_consummable_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_consummables/units_consummable/new.html.twig', [
            'units_consummable' => $unitsConsummable,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_units_consummable_show', methods: ['GET'])]
    public function show(UnitsConsummable $unitsConsummable): Response
    {
        return $this->render('admin_consummables/units_consummable/show.html.twig', [
            'units_consummable' => $unitsConsummable,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_units_consummable_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, UnitsConsummable $unitsConsummable, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UnitsConsummableType::class, $unitsConsummable);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success','Modifier une unitée avec succes');
            return $this->redirectToRoute('app_units_consummable_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_consummables/units_consummable/edit.html.twig', [
            'units_consummable' => $unitsConsummable,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_units_consummable_delete', methods: ['POST'])]
    public function delete(Request $request, UnitsConsummable $unitsConsummable, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$unitsConsummable->getId(), $request->request->get('_token'))) {
            $entityManager->remove($unitsConsummable);
            $entityManager->flush();
            $this->addFlash('success','Effacer une unitée avec succes');
        }

        return $this->redirectToRoute('app_units_consummable_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/crudTemplates/units_consummable/_delete_form.html.twig
<form method="post" action="{{ path('app_units_consummable_delete', {'id': units_consummable.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ units_consummable.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/crudTemplates/units_consummable/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/crudTemplates/units_consummable/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit UnitsConsummable{% endblock %}

{% block body %}
    <h1>Edit UnitsConsummable</h1>

    {{ include('/crudTemplates/units_consummable/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_units_consummable_index') }}">back to list</a>

    {{ include('/crudTemplates/units_consummable/_delete_form.html.twig') }}
{% endblock %}

app/templates/crudTemplates/units_consummable/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UnitsConsummable index{% endblock %}

{% block body %}
    <h1>UnitsConsummable index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_unit</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for units_consummable in units_consummables %}
            <tr>
                <td>{{ units_consummable.id }}</td>
                <td>{{ units_consummable.nameUnit }}</td>
                <td>
                    <a href="{{ path('app_units_consummable_show', {'id': units_consummable.id}) }}">show</a>
                    <a href="{{ path('app_units_consummable_edit', {'id': units_consummable.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_units_consummable_new') }}">Create new</a>
{% endblock %}

app/templates/crudTemplates/units_consummable/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UnitsConsummable{% endblock %}

{% block body %}
    <h1>Create new UnitsConsummable</h1>

    {{ include('/crudTemplates/units_consummable/_form.html.twig') }}

    <a href="{{ path('app_units_consummable_index') }}">back to list</a>
{% endblock %}

app/templates/crudTemplates/units_consummable/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UnitsConsummable{% endblock %}

{% block body %}
    <h1>UnitsConsummable</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ units_consummable.id }}</td>
            </tr>
            <tr>
                <th>Name_unit</th>
                <td>{{ units_consummable.nameUnit }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_units_consummable_index') }}">back to list</a>

    <a href="{{ path('app_units_consummable_edit', {'id': units_consummable.id}) }}">edit</a>

    {{ include('/crudTemplates/units_consummable/_delete_form.html.twig') }}
{% endblock %}